services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=${HOST_NAME:?error}
      - HTTP_USER=${USER_NAME:?error}
      - HTTP_PASSWORD=${PASSWD:?error}
    ports:
      - 8081:8081
    depends_on:
      - redis
    
volumes:
  redis-data: